create table if not exists public.downloads (
  id int8 generated by default as identity primary key,
  name text not null,
  description text not null,
  category text not null,
  thumbnail text not null,
  file_link text not null
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'downloads'
  ) then
    alter publication supabase_realtime add table public.downloads;
  end if;
end $$;

-- For a simple static frontend using only an anon key, the table must be readable.
-- Add/delete happens through password-checked RPC functions below.
alter table public.downloads enable row level security;

grant select on table public.downloads to anon;
revoke insert, update, delete on table public.downloads from anon;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'downloads'
      and policyname = 'Public can read downloads'
  ) then
    create policy "Public can read downloads"
    on public.downloads for select
    using (true);
  end if;
end $$;

drop policy if exists "Anon can add downloads" on public.downloads;
drop policy if exists "Anon can delete downloads" on public.downloads;

create or replace function public.admin_add_download(
  admin_password text,
  p_name text,
  p_description text,
  p_category text,
  p_thumbnail text,
  p_file_link text
)
returns int8
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id int8;
begin
  if admin_password <> 'jaya@2911' then
    raise exception 'Invalid admin password';
  end if;

  insert into public.downloads (name, description, category, thumbnail, file_link)
  values (p_name, p_description, p_category, p_thumbnail, p_file_link)
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.admin_delete_download(
  admin_password text,
  p_id int8
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if admin_password <> 'jaya@2911' then
    raise exception 'Invalid admin password';
  end if;

  delete from public.downloads
  where id = p_id;
end;
$$;

grant execute on function public.admin_add_download(text, text, text, text, text, text) to anon;
grant execute on function public.admin_delete_download(text, int8) to anon;
